This project is a basic RNN example for next word prediction. 

In [ ]:
import numpy as np
import tensorflow as tf


c:\Users\shara\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [ ]:
# import the text data into a variable
with open('Australia_History.txt', 'r', encoding='utf-8') as file:
    australiaHistory= file.read()

In [4]:
australiaHistory


'History of Australia for the Curious Traveller\n\nMillions of years in the making, Australia has an extraordinary history. The people, places and events that have shaped this country are celebrated in the form of unforgettable festivals, museums, walks, guided tours and more. History lovers will be richly rewarded with one-of-a-kind experiences that delve into the backstory of the island nation.\n\nPrehistoric\n\nDinosaurs lived from about 250 to 65 million years ago and there’s plenty of fossil evidence that shows a diverse range roamed Australia’s ancient lands.\n\nYou can follow in the footsteps of these prehistoric giants by joining the five-day Australian Dinosaur Trail in Queensland, which includes a visit to the site of the only known dinosaur stampede on the planet. These fossilised dinosaur footprints actually inspired the stampede scene in the blockbuster film, Jurassic Park. Not far from here you will also find the Australian Age of Dinosaurs Museum, home of the world’s lar

In [5]:
#To convert the text into numbers, we can use the Tokenizer class from Keras. This will create a mapping of each unique word to a unique integer.
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([australiaHistory])

In [6]:
tokenizer.get_config()

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"history": 3, "of": 50, "australia": 11, "for": 12, "the": 82, "curious": 1, "traveller": 1, "millions": 1, "years": 8, "in": 36, "making": 1, "has": 1, "an": 10, "extraordinary": 1, "people": 3, "places": 2, "and": 37, "events": 1, "that": 5, "have": 3, "shaped": 1, "this": 3, "country": 4, "are": 2, "celebrated": 1, "form": 2, "unforgettable": 1, "festivals": 1, "museums": 1, "walks": 2, "guided": 3, "tours": 1, "more": 7, "lovers": 1, "will": 3, "be": 5, "richly": 1, "rewarded": 1, "with": 4, "one": 3, "a": 21, "kind": 1, "experiences": 1, "delve": 1, "into": 2, "backstory": 1, "island": 4, "nation": 1, "prehistoric": 2, "dinosaurs": 2, "lived": 2, "from": 11, "about": 4, "250": 1, "to": 35, "65": 1, "million": 2, "ago": 2, "there\\u2019s": 4, "plenty": 1, "fossil": 1, "evidence": 1, "shows": 1, "dive

In [ ]:
#check the word index mapping
tokenizer.word_index

{'the': 1,
 'of': 2,
 'and': 3,
 'in': 4,
 'to': 5,
 'a': 6,
 'for': 7,
 'australian': 8,
 'australia': 9,
 'from': 10,
 'on': 11,
 'an': 12,
 'were': 13,
 'years': 14,
 'you': 15,
 'by': 16,
 'at': 17,
 'first': 18,
 'more': 19,
 'can': 20,
 'was': 21,
 'as': 22,
 'gold': 23,
 'sydney': 24,
 'life': 25,
 'is': 26,
 'tour': 27,
 'that': 28,
 'be': 29,
 'dinosaur': 30,
 'museum': 31,
 'their': 32,
 'take': 33,
 'or': 34,
 'convicts': 35,
 'country': 36,
 'with': 37,
 'island': 38,
 'about': 39,
 'there’s': 40,
 'these': 41,
 'only': 42,
 'here': 43,
 'home': 44,
 'aboriginal': 45,
 'many': 46,
 'learn': 47,
 'new': 48,
 'south': 49,
 'history': 50,
 'people': 51,
 'have': 52,
 'this': 53,
 'guided': 54,
 'will': 55,
 'one': 56,
 'day': 57,
 'site': 58,
 'not': 59,
 'also': 60,
 'west': 61,
 'coast': 62,
 'continent': 63,
 'than': 64,
 '000': 65,
 'european': 66,
 'colonisation': 67,
 'its': 68,
 'across': 69,
 'all': 70,
 'journey': 71,
 'place': 72,
 'explore': 73,
 'stories': 74,
 'ex

In [ ]:
#to see the sentences in the given text
input_sequences = []
text=australiaHistory.replace('\n', '.')
for sentence in text.split('.'):
    sentence = sentence.strip()# to avoid any leading or trailing whitespace and removing any empty sentences
    if sentence:
        print (sentence)
        token_list = tokenizer.texts_to_sequences([sentence])[0]
        print (token_list)


History of Australia for the Curious Traveller
[50, 2, 9, 7, 1, 172, 173]
Millions of years in the making, Australia has an extraordinary history
[174, 2, 14, 4, 1, 175, 9, 176, 12, 177, 50]
The people, places and events that have shaped this country are celebrated in the form of unforgettable festivals, museums, walks, guided tours and more
[1, 51, 90, 3, 178, 28, 52, 179, 53, 36, 91, 180, 4, 1, 92, 2, 181, 182, 183, 93, 54, 184, 3, 19]
History lovers will be richly rewarded with one-of-a-kind experiences that delve into the backstory of the island nation
[50, 185, 55, 29, 186, 187, 37, 56, 2, 6, 188, 189, 28, 190, 94, 1, 191, 2, 1, 38, 192]
Prehistoric
[95]
Dinosaurs lived from about 250 to 65 million years ago and there’s plenty of fossil evidence that shows a diverse range roamed Australia’s ancient lands
[96, 97, 10, 39, 193, 5, 194, 98, 14, 99, 3, 40, 195, 2, 196, 197, 28, 198, 6, 199, 200, 201, 100, 101, 202]
You can follow in the footsteps of these prehistoric giants by joining

In [ ]:
#create input vs output format for above sentneces. 
input_sequences = []
text=australiaHistory.replace('\n', '.')
for sentence in text.split('.'):
    sentence = sentence.strip()# to avoid any leading or trailing whitespace and removing any empty sentences
    if sentence:
        token_list = tokenizer.texts_to_sequences([sentence])[0]
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
            input_sequences.append(n_gram_sequence)

In [40]:
input_sequences[2]#check on first 5 sequences

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       50,  2,  9,  7], dtype=int32)

In [ ]:
#to arrange the all sequences into same length, we can use the pad_sequences function from Keras. This will add padding to the sequences so that they all have the same length.
#first we need to find the higest input sequence length
max_sequence_len = max([len(x) for x in input_sequences])
max_sequence_len

55

In [49]:
#Conduct padding
input_sequences = tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')#padding at the beginning of the sequence
input_sequences[:5]#check on first 5 sequences after padding

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  50,   2],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         50,   2,   9],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  50,
          2,   9,   7],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,

In [64]:
#create x and y for model training
X = input_sequences[:,:-1] #all the columns except the last one will be our input
y = input_sequences[:,-1]#the last column will be our output


In [65]:
X[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, 50], dtype=int32)

In [66]:
y

array([  2,   9,   7, ...,  31,   4, 577], shape=(1160,), dtype=int32)

In [75]:
#curently y has integer values representing the next word in the sequence. We need to convert these integer values into one-hot encoded vectors so that we can use them for training our model.
#first we have to dientify the no of different words in the text, which will be the size of our vocabulary. We can get this from the tokenizer.word_index
vocab_size = len(tokenizer.word_index) + 1 #we add 1 because the word index starts from 1, and we need to account for the 0 index which is used for padding
Y = np.array(tf.keras.utils.to_categorical(y, num_classes=vocab_size))

In [ ]:
Y[10]#check with 10th value of Y to see the one hot encoding

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
#Now we can create the model using an embedding layer and an LSTM layer. The embedding layer will convert the integer values in X into dense vectors of fixed size, and the LSTM layer will learn the patterns in the sequences to predict the next word.
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(max_sequence_len - 1,)))#input layer with shape as the length of the input sequences (which is max_sequence_len - 1 because we have removed the last word for the output)
model.add(tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=80))#embedding layer with input dimension as the size of the vocabulary and output dimension as 80 (this is a hyperparameter that we can tune)
model.add(tf.keras.layers.LSTM(100))#LSTM layer with 100 units
model.add(tf.keras.layers.Dense(vocab_size, activation='softmax'))#output layer with softmax activation(becuase this a multi class classification) to get probabilities for each word in the vocabulary

In [88]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 54, 80)         │        46,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 100)            │        72,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 578)            │        58,378 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 177,018 (691.48 KB)

 Trainable params: 177,018 (691.48 KB)

 Non-trainable params: 0 (0.00 B)

In [89]:
#compile the model with categorical crossentropy loss and adam optimizer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [90]:
#train the model using 100 epochs
history=model.fit(X, Y, epochs=100)

Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.0534 - loss: 6.1628
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0664 - loss: 5.8250
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0664 - loss: 5.7237
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0664 - loss: 5.6817
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0664 - loss: 5.6229
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0664 - loss: 5.5466
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0664 - loss: 5.4512
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0698 - loss: 5.3527
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0871 - loss: 5.2475
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0905 - loss: 5.1450
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1009 - loss: 5.0371
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [92]:
#now we can predict using this model.Let us consider below input seqeunce
input_text="the first people to arrive in Australia" 

In [93]:
#arrange the tokenlist for given input text
token_list_for_prediction = tokenizer.texts_to_sequences([input_text])[0]
print (token_list_for_prediction)  

[1, 18, 51, 5, 4, 9]


In [94]:
#add padding to the token list list to make it same length as the input sequences used for training
token_list_for_prediction = tf.keras.preprocessing.sequence.pad_sequences([token_list_for_prediction], maxlen=max_sequence_len-1, padding='pre')
token_list_for_prediction

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1, 18, 51,  5,  4,  9]], dtype=int32)

In [96]:
#take the next word prediction from the model
predicted_value=np.argmax(model.predict(token_list_for_prediction))#the model will return a probability distribution over the vocabulary, and we can use np.argmax to get the index of the word with the highest probability, which will be our predicted next word.
print (predicted_value)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
3


In [97]:
#check the predicted word from the index
for word, index in tokenizer.word_index.items():
    if index == predicted_value:
        print (word)
        break

and


In [110]:
"""
We can use the same approch to predict multiple words by adding the predicted word to the input sequence and predicting again. 
This way we can generate a sequence of words based on the given input text.
"""
input_text="on April 25 "
for _ in range(10):#predict next 10 words
    token_list_for_prediction = tokenizer.texts_to_sequences([input_text])[0]
    token_list_for_prediction = tf.keras.preprocessing.sequence.pad_sequences([token_list_for_prediction], maxlen=max_sequence_len-1, padding='pre')
    predicted_value=np.argmax(model.predict(token_list_for_prediction))
    for word, index in tokenizer.word_index.items():
        if index == predicted_value:
            input_text += ' ' + word
            break
print (input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
on April 25  anzac day is commemorated across the country with dawn services
